### ISSUE TITLE
Support for any

### ISSUE THREAD

**Issue by skadefro** [z26zheng/azure-documentdb-odata-sql#1]
Is there any plans to support any/all queries ?

like in array of strings
$filter=tags/any(x: x eq 'car')

or array of complex type
$filter=address/any(x: x.zipcode eq '8370')

I see you have code for parsing it, but the SQL it returns fails when parsed to DocumentDB.

**Comment by egbertn** [comment]
I have added this in my fork of this project (z27zheng seems to have abandoned further development). However, this not (yet) a nuget package. Just get it from github.
https://github.com/egbertn/azure-documentdb-odata-sql
